### ISSUE TITLE
We cannot get the same result as your demonstrate in class

### ISSUE THREAD

**Issue by buaajjg** [CSYE6225/UnixSysProgramming#8]
I use "curl -o" to download a big file from the server, at the  beginning  the cpu and IO changed a lot, but if we create many duplicate sessions at same time, the downloading speed will reduce from 30-50M to 300-500K, the more sessions, the lower the speed is , So it is difficult to hit the limit of connection. Could you give me a hint to solve this?

**Comment by buaajjg** [comment]
![02](https://cloud.githubusercontent.com/assets/14844277/13903250/7448b564-ee30-11e5-9614-ed399de12e5d.jpg)
![03](https://cloud.githubusercontent.com/assets/14844277/13903251/7ef9db96-ee30-11e5-83e6-9439835abf75.jpg)
![05](https://cloud.githubusercontent.com/assets/14844277/13903254/95706660-ee30-11e5-9d29-2f45b6f089b2.jpg)

![04](https://cloud.githubusercontent.com/assets/14844277/13903253/896ce24e-ee30-11e5-872c-785b2dccc292.jpg)
![06](https://cloud.githubusercontent.com/assets/14844277/13903258/a0a614b2-ee30-11e5-956c-f50e92d9c6cb.jpg)

**Comment by buaajjg** [comment]
the top two screen is two servers, the bottom left is the balancer, and the bottom right screens are the clients.

**Comment by yahavb** [comment]
It is very difficult to understand your point from the screenshots. Please try to be as crisp as possible. 
What is the architecture you are trying to enable? What is the workload you are trying to generate? What is the command you are executing that does not work for you? What is the problem and the help you think I can provide?
Please DO NOT add any screen shot. Also, be concise as possible and to the point.

**Comment by buaajjg** [comment]
thanks, I' ll try it by my own
