### ISSUE TITLE
Unable to access EC2 instances...

### ISSUE THREAD

**Issue by notedboi** [CSYE6225/UnixSysProgramming#9]
Can not start an EC2 instance which has been initialized or launch a new one. In both two situations it says "This action/request has been administratively disabled."  And technical support is unreachable when user is under AWS free tier... Had looked through developer forums but nothing valid. Don't know whether it has something do with the load as I tried load testing about 6 hours..

**Comment by yahavb** [comment]
how about you try Azure of GCE
On Mar 30, 2016, at 7:49 PM, Hekuan Yang <notifications@github.com<mailto:notifications@github.com>> wrote:

Can not start an EC2 instance which has been initialized or launch a new one. In both two situations it says "This action/request has been administratively disabled." And technical support is unreachable when user is under AWS free tier... Had looked through developer forums but nothing valid. Don't know whether it has something do with the load as I tried load testing about 6 hours..
